### ISSUE TITLE
network 012-coordinate model requirements

### ISSUE THREAD

**Issue by jinjingfarm** [InterPSS-Project/ExtendedPiecewiseAlgo#1]
Tony - please describe the details of network 012-coordinate model details at the following Wkik page 

https://github.com/InterPSS-Project/ExtendedPiecewiseAlgo/wiki/Network-012-Coordinate-Model

**Comment by thuang** [comment]
Mike, I am not sure about what kind of details you would like to document here. 012-coordinate is the default representation used by InterPSS core objects. What I can think about related to this topic are:
 --  the 012 network representation
 --  build network equivalent in 012 coordinate
 --  transformation between 012 and ABC

**Comment by jinjingfarm** [comment]
Tony, yes, these are points we can start with.

**Comment by jinjingfarm** [comment]
Tony, also do the same for the ABC three-phase model at the Network ABC-Coordinate Model page.
