### ISSUE TITLE
sub-network vs sub-area concept

### ISSUE THREAD

**Issue by thuang** [InterPSS-Project/ExtendedPiecewiseAlgo#2]
Mike, I saw your opinion on the choice between the two. If sub-area is to replace sub-network concept, I don't think the sub-area concept  is better than the subnetwork concept, as our existing algorithms are all applied to network objects.  If it is to add one more modeling level below the sub-network level, this would make the structure more complicated to manage. Even for the later scenario, we can use a " subworks within a subnetwork"  structure to handle the same modeling requirement.

In the current implementation, the sub-area concept is used instead of the subnetwork concept.  I can see that subarea concept works well with the linear network solution algorithm. However,  the sub-area concept means changing to a new modeling practice, which it is difficult to fit it into existing simulation algorithm/framework.

**Comment by jinjingfarm** [comment]
Tony, if we are going to break a large network into many sub-networks for parallel simulation, I think, most of the sub networks are linear. I can see the following requirements:

1) A large network is first broken into a set of linear sub areas
2) If necessary, as certain simulation point, some of the sub areas are turned to sub networks for ABC or EMTP representation 
3) A sub network can be turned back to sub area

One of the key issues of this implementation is to provide a unified way for the subarea/sub-network transformation.
